const fs = require('fs');
const path = require('path');
const https = require('https');
const crypto = require('crypto');

const ROOT = __dirname;
// DIST and the registry path can be overridden via env vars so the smoke
// test in test/build.test.mjs can run a parallel build against a temp
// registry without clobbering real outputs. Defaults keep prod behavior
// (CF Pages + GH Actions) unchanged.
const DIST = process.env.FAS_DIST
  ? path.resolve(process.env.FAS_DIST)
  : path.join(ROOT, 'dist');
const REGISTRY_PATH = process.env.FAS_REGISTRY_PATH
  ? path.resolve(process.env.FAS_REGISTRY_PATH)
  : path.join(ROOT, 'registry.json');

// Read registry
const registry = JSON.parse(fs.readFileSync(REGISTRY_PATH, 'utf8'));
const apps = registry.apps;

// --- Registry shape validator (security: stop malformed/malicious entries at
// build time before they get a chance to render). Loud failure is intentional
// — a bad registry should break the build, not silently ship broken HTML. ---
const ID_RE = /^[a-z0-9][a-z0-9-]*$/;
const COLOR_RE = /^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/;
const URL_RE = /^https:\/\/[a-z0-9.-]+\.freeappstore\.online(?:\/.*)?$/;
// Length caps prevent registry-bloat DoS (a 1MB name becomes 1MB of HTML);
// control-char ban catches accidental \r\n breaking attribute quoting.
function safeText(s, max) {
  return typeof s === 'string' && s.length > 0 && s.length <= max && !/[\x00-\x1f\x7f]/.test(s);
}
function validateRegistry(items) {
  const errors = [];
  const seenIds = new Set();
  for (const a of items) {
    if (!a.id || !ID_RE.test(a.id)) errors.push(`bad id: ${JSON.stringify(a.id)}`);
    else if (seenIds.has(a.id)) errors.push(`duplicate id: ${JSON.stringify(a.id)}`);
    else seenIds.add(a.id);
    if (!safeText(a.name, 80)) errors.push(`${a.id}: name must be 1-80 chars without control chars`);
    if (!a.appUrl || !URL_RE.test(a.appUrl)) errors.push(`${a.id}: appUrl must be https://*.freeappstore.online, got ${JSON.stringify(a.appUrl)}`);
    if (a.iconBg && !COLOR_RE.test(a.iconBg)) errors.push(`${a.id}: iconBg must be a #hex color, got ${JSON.stringify(a.iconBg)}`);
    if (a.category != null && !safeText(a.category, 80)) errors.push(`${a.id}: bad category ${JSON.stringify(a.category)}`);
    if (a.description != null && !safeText(a.description, 500)) errors.push(`${a.id}: description must be 1-500 chars without control chars`);
    if (a.developer != null && !safeText(a.developer, 60)) errors.push(`${a.id}: bad developer ${JSON.stringify(a.developer)}`);
    if (a.repo != null && (typeof a.repo !== 'string' || a.repo.length > 100 || !/^[\w.-]+\/[\w.-]+$/.test(a.repo))) {
      errors.push(`${a.id}: repo must be "owner/name", got ${JSON.stringify(a.repo)}`);
    }
  }
  if (errors.length) {
    console.error('Registry validation failed:\n  - ' + errors.join('\n  - '));
    process.exit(1);
  }
}
validateRegistry(apps);

// Read quality scores (generated by scripts/quality-scan.js)
const scoresPath = path.join(DIST, 'quality', 'scores.json');
const qualityScores = fs.existsSync(scoresPath) ? JSON.parse(fs.readFileSync(scoresPath, 'utf8')) : {};

// Shared header partial — injected into every page via {{HEADER}} placeholder
const headerPartial = fs.readFileSync(path.join(ROOT, 'partials', 'header.html'), 'utf8');
const footerPartial = fs.readFileSync(path.join(ROOT, 'partials', 'footer.html'), 'utf8');
function injectPartials(html) { return html.replaceAll('{{HEADER}}', headerPartial).replaceAll('{{FOOTER}}', footerPartial); }

// Read templates (partials injected on load)
const indexTemplate = injectPartials(fs.readFileSync(path.join(ROOT, 'templates', 'index.html'), 'utf8'));
const detailTemplate = injectPartials(fs.readFileSync(path.join(ROOT, 'templates', 'app-detail.html'), 'utf8'));

// CF Web Analytics — token comes from FAS_CF_BEACON_TOKEN at build time. If
// unset (local dev), the placeholder is replaced with an empty string so the
// page still validates. The CSP allowlist for static.cloudflareinsights.com
// is added unconditionally so flipping the token on later doesn't require a
// CSP redeploy.
const CF_BEACON_TOKEN = (process.env.FAS_CF_BEACON_TOKEN || '').trim();
const CF_BEACON_SNIPPET = CF_BEACON_TOKEN && /^[a-f0-9]{32,}$/i.test(CF_BEACON_TOKEN)
  ? `<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"token":"${CF_BEACON_TOKEN}"}'></script>`
  : '<!-- CF Web Analytics: FAS_CF_BEACON_TOKEN unset at build time -->';

// Helper: format category label (brain-training -> Brain Training)
function categoryLabel(cat) {
  return cat.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
}

// Helper: type label
function typeLabel(type) {
  return type === 'standalone' ? 'Standalone (works offline)' : 'Connected (requires internet)';
}

// --- GitHub API helpers (used to source first-published + commit log) ---

const GH_TOKEN = process.env.GITHUB_TOKEN || process.env.GH_TOKEN || '';

function ghFetch(urlPath) {
  return new Promise((resolve, reject) => {
    const headers = {
      'User-Agent': 'freeappstore-build',
      'Accept': 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
    };
    if (GH_TOKEN) headers['Authorization'] = `Bearer ${GH_TOKEN}`;
    const req = https.request(
      { hostname: 'api.github.com', path: urlPath, method: 'GET', headers },
      (res) => {
        let data = '';
        res.on('data', (chunk) => (data += chunk));
        res.on('end', () => {
          if (res.statusCode >= 200 && res.statusCode < 300) {
            try { resolve(JSON.parse(data)); }
            catch (e) { reject(new Error(`bad JSON from ${urlPath}: ${e.message}`)); }
          } else {
            // Non-fatal — caller should fall back to "no data" rather than fail the build.
            // Surface the rate-limit case clearly.
            const isRateLimit = res.statusCode === 403 && /rate limit/i.test(data);
            reject(new Error(`${urlPath} → ${res.statusCode}${isRateLimit ? ' (rate limited)' : ''}`));
          }
        });
      },
    );
    req.on('error', reject);
    req.end();
  });
}

const FMT_DATE = new Intl.DateTimeFormat('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
const FMT_SHORT = new Intl.DateTimeFormat('en-US', { year: 'numeric', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' });

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Trim the GitHub API responses to only the fields renderHistorySection
 * and renderPublishedLine actually read. The full responses are ~14 KB
 * per app × 25 apps ≈ 350 KB; the trimmed shape is ~600 bytes per app.
 * Smaller cache = smaller diffs in CI commits = less repo churn.
 */
function compactHistory(meta, commits) {
  return {
    meta: meta
      ? {
          created_at: meta.created_at ?? null,
          pushed_at: meta.pushed_at ?? null,
        }
      : null,
    commits: Array.isArray(commits)
      ? commits.map((c) => ({
          sha: c.sha,
          html_url: c.html_url,
          commit: {
            message: c.commit?.message ?? '',
            author: { date: c.commit?.author?.date ?? c.commit?.committer?.date ?? null },
          },
        }))
      : null,
  };
}

async function fetchAppHistory(repo) {
  // repo is "owner/name". Two parallel calls: repo metadata for created_at,
  // and the last 3 commits for the changelog. Failures degrade gracefully.
  try {
    const [meta, commits] = await Promise.all([
      ghFetch(`/repos/${repo}`),
      ghFetch(`/repos/${repo}/commits?per_page=3`),
    ]);
    return compactHistory(meta, commits);
  } catch (err) {
    console.warn(`  ! could not fetch history for ${repo}: ${err.message}`);
    return { meta: null, commits: null };
  }
}

// --- History cache (data/commit-history.json) ---
//
// CF Pages runs its own GitHub-integration build that doesn't have
// GITHUB_TOKEN, so it hits the 60/hr unauthenticated rate limit and
// renders the fallback. Caching the histories in the repo lets that
// no-token build still produce correct output — it falls back to the
// cache when the API call fails. The scheduled GH-Actions deploy
// refreshes the cache every 6h.
const CACHE_PATH = path.join(ROOT, 'data', 'commit-history.json');

function readCache() {
  try {
    return JSON.parse(fs.readFileSync(CACHE_PATH, 'utf8'));
  } catch {
    return {};
  }
}

function writeCache(cache) {
  fs.mkdirSync(path.dirname(CACHE_PATH), { recursive: true });
  fs.writeFileSync(CACHE_PATH, JSON.stringify(cache, null, 2) + '\n');
}

/**
 * Fetch history for every app, falling back to the cache when GitHub
 * fails. Returns the histories array AND the updated cache (callers
 * write it to disk so the next build sees fresh data even if the API
 * is rate-limited at that time).
 */
async function fetchAllHistories(apps) {
  const cache = readCache();
  const histories = await Promise.all(
    apps.map(async (app) => {
      const fresh = await fetchAppHistory(app.repo);
      if (fresh.commits) {
        // Cache is keyed by repo so re-ordering registry doesn't churn.
        cache[app.repo] = fresh;
        return fresh;
      }
      // API failed — return the last good data, if any.
      const cached = cache[app.repo];
      if (cached?.commits) return cached;
      return fresh; // both null
    }),
  );
  writeCache(cache);
  return histories;
}

function renderHistorySection(repo, history) {
  const githubAllUrl = `https://github.com/${repo}/commits/main`;
  if (!history.commits || history.commits.length === 0) {
    return `<section class="app-section">
      <h2>Recent updates</h2>
      <p class="text-muted-em">No updates yet — check back after the first deploy.</p>
      <p><a class="source-link" href="${githubAllUrl}" target="_blank" rel="noopener">See full history on GitHub &rarr;</a></p>
    </section>`;
  }
  const items = history.commits.map((c) => {
    const date = new Date(c.commit.author?.date ?? c.commit.committer?.date);
    const isoDate = date.toISOString().slice(0, 10);
    const shortDate = FMT_SHORT.format(date);
    // Commit messages are user-provided — escape and trim to first line.
    const firstLine = (c.commit.message || '').split('\n')[0].trim();
    const msg = escapeHtml(firstLine).slice(0, 140);
    const sha = c.sha.slice(0, 7);
    return `<li class="version-row">
      <time datetime="${isoDate}" class="version-date">${shortDate}</time>
      <span class="version-msg">${msg}</span>
      <a class="version-sha" href="${c.html_url}" target="_blank" rel="noopener">${sha}</a>
    </li>`;
  }).join('\n');
  return `<section class="app-section">
      <h2>Recent updates</h2>
      <ul class="version-log">
${items}
      </ul>
      <p class="mt-half"><a class="source-link" href="${githubAllUrl}" target="_blank" rel="noopener">See full history on GitHub &rarr;</a></p>
    </section>`;
}

function renderPublishedLine(history) {
  if (!history.meta) return '';
  const created = history.meta.created_at ? new Date(history.meta.created_at) : null;
  const lastCommit = history.commits?.[0];
  const updated = lastCommit?.commit?.author?.date
    ? new Date(lastCommit.commit.author.date)
    : history.meta.pushed_at ? new Date(history.meta.pushed_at) : null;
  const parts = [];
  if (created) {
    parts.push(`First published <time datetime="${created.toISOString().slice(0,10)}">${FMT_DATE.format(created)}</time>`);
  }
  if (updated) {
    parts.push(`last updated <time datetime="${updated.toISOString().slice(0,10)}">${FMT_DATE.format(updated)}</time>`);
  }
  if (parts.length === 0) return '';
  return `<p class="published-line">${parts.join(' &middot; ')}</p>`;
}

// Ensure dist directories exist
fs.mkdirSync(path.join(DIST, 'apps'), { recursive: true });

// --- Generate index.html ---

// Build app cards — compact letter-badge layout, Figma 2026
// Per-card icon backgrounds are NOT inline styles. They're written to
// dist/card-styles.css (loaded via <link>) so a malformed iconBg slipping
// past the validator (regex regression, e.g.) cannot end up as a
// style="..." attribute. The CSS file is `'self'` per CSP.
// Dual selector so the same generated rule paints (a) the icon inside an
// .app-card on the storefront grid AND (b) the .app-icon on the per-app
// detail page hero. Detail-page templates set data-id directly on the icon
// element; storefront cards keep data-id on the wrapping card.
const cardIconBackgrounds = apps
  .map(app => {
    const safeId = escapeAttrCss(app.id);
    const bg = app.iconBg || '#2563eb';
    return `.app-card[data-id="${safeId}"] .app-icon, .app-icon[data-id="${safeId}"] { background: ${bg}; }`;
  })
  .join('\n');
function escapeAttrCss(s) {
  // The validator already constrains id to [a-z0-9-]+ so this is belt-and-suspenders.
  return String(s).replace(/[^a-z0-9_-]/gi, '_');
}

function renderAppCard(app, published) {
  const q = qualityScores[app.id];
  const qualityBadge = q && q.grade
    ? `<a href="/quality/${escapeHtml(app.id)}/" class="quality-badge grade-${q.grade.toLowerCase()}" title="Code quality: ${q.score}/100">${q.grade}</a>`
    : '';
  // Letter fallback lives on a data-attribute; storefront.js binds the
  // img.error listener and reads it. No more JS-string-in-HTML-attribute splicing.
  const letter = escapeHtml((app.name || '?').trim().charAt(0).toUpperCase());
  const authAttr = app.requiresAuth ? ' data-requires-auth="1"' : '';
  const publishedAttr = published ? ` data-published="${escapeHtml(published)}"` : '';
  const iconEmoji = app.icon || `&#${(app.name || '?').codePointAt(0)};`;
  return `        <div class="app-card compact" data-id="${escapeHtml(app.id)}" data-name="${escapeHtml(app.name)}" data-category="${escapeHtml(app.category)}" data-about="/apps/${escapeHtml(app.id)}"${authAttr}${publishedAttr}>
          <div class="app-icon" data-letter="${letter}">
            <span class="app-emoji" aria-hidden="true">${iconEmoji}</span>
          </div>
          <div class="app-body">
            <span class="app-name">${escapeHtml(app.name)}${qualityBadge}</span>
            <span class="app-meta">${escapeHtml(categoryLabel(app.category))}</span>
          </div>
          <button class="vote-btn" type="button" data-app-id="${escapeHtml(app.id)}" aria-label="Vote for ${escapeHtml(app.name)}" aria-pressed="false">
            <svg class="vote-icon" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>
            <span class="vote-count">0</span>
          </button>
          <a href="${escapeHtml(app.appUrl)}" target="_blank" rel="noopener" class="app-cta" aria-label="Open ${escapeHtml(app.name)}">
            <svg viewBox="0 0 24 24" aria-hidden="true"><polygon points="6,4 20,12 6,20" /></svg>
            <span class="cta-label">Open</span>
          </a>
        </div>`;
}

// Inline author attribution: a pill linking to the per-author profile page
// at /u/<username>.html. Avatar served by avatars.githubusercontent.com
// (already in the storefront's CSP img-src). For apps with no creatorGithub
// yet (legacy entries pre-author-system), fall back to the plain developer
// string with no link, so old cards keep rendering cleanly.
const renderAuthorChip = (app) => {
  if (app.creatorGithub) {
    const user = escapeHtml(app.creatorGithub);
    return `<a href="/u/${user}.html" class="author-chip">` +
      `<img src="https://avatars.githubusercontent.com/${user}?size=40" alt="" class="author-chip-avatar" loading="lazy" width="20" height="20" />` +
      `<span class="author-chip-name">@${user}</span>` +
      `</a>`;
  }
  return escapeHtml(app.developer || 'FreeAppStore');
};

// appCards is generated inside the async IIFE below so it can use
// histories[i].meta.created_at to stamp data-published on each card.

// indexHtml is finalized inside the async IIFE below — cross-store
// registry fetch is async, and we want to embed it into the page.
// Compute SHA-256 of the inline no-flash theme bootstrap so the CSP can
// whitelist that exact script without 'unsafe-inline'. The bootstrap is the
// first <script>…</script> block inside <head> in the template.
const inlineScriptMatch = indexTemplate.match(/<head>[\s\S]*?<script>([\s\S]*?)<\/script>/);
if (!inlineScriptMatch) {
  console.error('Could not locate the inline bootstrap <script> for CSP hashing');
  process.exit(1);
}
const inlineScriptHash = 'sha256-' + crypto.createHash('sha256').update(inlineScriptMatch[1]).digest('base64');

// Subresource Integrity hashes for local script files. Each <script src="...">
// in the templates gets an integrity="sha256-..." attribute so the browser
// refuses to execute the file if it's been tampered with on the CDN.
// Same-origin doesn't need crossorigin="anonymous"; we skip it to avoid CORS.
function sriHash(filename) {
  const content = fs.readFileSync(path.join(ROOT, filename));
  return 'sha256-' + crypto.createHash('sha256').update(content).digest('base64');
}
// Short content-version token (first 10 hex chars of the SHA-256). Used as
// a URL query param (?v=<token>) so every deploy that changes a file gets a
// new URL. The edge can then cache the asset immutably — the URL changes
// whenever the content changes, so a stale-cached copy is never served for
// a URL that the fresh HTML references.
function contentVersion(filename) {
  const content = fs.readFileSync(path.join(ROOT, filename));
  return crypto.createHash('sha256').update(content).digest('hex').slice(0, 10);
}
const sriHashes = {
  SEARCH_JS: sriHash('search.js'),
  STOREFRONT_JS: sriHash('storefront.js'),
  AUTH_JS: sriHash('auth.js'),
  DETAIL_PAGE_JS: sriHash('detail-page.js'),
  GET_STARTED_JS: sriHash('get-started.js'),
  QUALITY_JS: sriHash('quality.js'),
  ANALYTICS_JS: sriHash('analytics.js'),
  PRISM_JS: sriHash('prism.js'),
  PRISM_AUTODETECT_JS: sriHash('prism-autodetect.js'),
  SETTINGS_JS: sriHash('settings.js'),
};
// Content-version tokens for the same set of assets (same read, different encoding).
const contentVersions = {
  SEARCH_JS: contentVersion('search.js'),
  STOREFRONT_JS: contentVersion('storefront.js'),
  AUTH_JS: contentVersion('auth.js'),
  DETAIL_PAGE_JS: contentVersion('detail-page.js'),
  GET_STARTED_JS: contentVersion('get-started.js'),
  QUALITY_JS: contentVersion('quality.js'),
  ANALYTICS_JS: contentVersion('analytics.js'),
  PRISM_JS: contentVersion('prism.js'),
  PRISM_AUTODETECT_JS: contentVersion('prism-autodetect.js'),
  SETTINGS_JS: contentVersion('settings.js'),
};

const categoryMap = new Map();
for (const app of apps) {
  const key = app.category.toLowerCase();
  if (!categoryMap.has(key)) categoryMap.set(key, categoryLabel(app.category));
}
const categories = [...categoryMap.entries()].sort((a, b) => a[1].localeCompare(b[1]));
const categoryFilters = categories
  .map(([key, label]) => `<button class="filter-btn" type="button" data-category="${escapeHtml(key)}">${escapeHtml(label)}</button>`)
  .join('\n        ');

// {{APPS_GRID}} is replaced inside the async IIFE after histories are fetched
// so each card can carry data-published from histories[i].meta.created_at.
let indexHtml = indexTemplate
  .replace('__CF_BEACON__', CF_BEACON_SNIPPET)
  .replace('{{INLINE_SCRIPT_HASH}}', inlineScriptHash)
  .replace('{{APPS_COUNT}}', String(apps.length))
  .replace('{{CATEGORY_FILTERS}}', categoryFilters);

// Apply SRI hashes and content-version tokens.
// SRI placeholders: {{SRI_AUTH_JS}} → integrity value
// Version placeholders: {{VER_AUTH_JS}} → short hex token used in src="...?v=<token>"
for (const [k, v] of Object.entries(sriHashes)) {
  indexHtml = indexHtml.replaceAll(`{{SRI_${k}}}`, v);
}
for (const [k, v] of Object.entries(contentVersions)) {
  indexHtml = indexHtml.replaceAll(`{{VER_${k}}}`, v);
}

// --- Generate app detail pages ---
// Fetch histories in parallel — 26 apps × 2 calls = 52 requests, well under
// authenticated GitHub rate limits (5000/hr) and ~5–10s wall time.
// Wrapped in async IIFE because this file is CJS (no top-level await).

async function fetchAuditSummary() {
  // Fetch the latest audit summary from /v1/audit. Failures degrade
  // gracefully — the audit badge just doesn't render. Falls back to
  // an empty map so all apps render the "not yet audited" state.
  try {
    const res = await new Promise((resolve, reject) => {
      const req = https.request(
        { hostname: 'api.freeappstore.online', path: '/v1/audit?store=apps', method: 'GET' },
        (r) => {
          let data = '';
          r.on('data', (c) => (data += c));
          r.on('end', () => resolve({ status: r.statusCode, body: data }));
        },
      );
      req.on('error', reject);
      req.end();
    });
    if (res.status !== 200) return new Map();
    const parsed = JSON.parse(res.body);
    const map = new Map();
    for (const s of parsed.summary ?? []) map.set(s.appId, s);
    return map;
  } catch (err) {
    console.warn(`  ! could not fetch audit summary: ${err.message}`);
    return new Map();
  }
}

function renderCodeQualityBadge(appId) {
  const q = qualityScores[appId];
  if (!q || !q.grade) return '';
  const cls = q.score >= 80 ? 'audit-pass' : q.score >= 60 ? 'audit-warn' : 'audit-fail';
  return `<p class="audit-badge ${cls}"><span class="dot"></span> Code quality: <strong>${q.grade}</strong> (${q.score}/100) &middot; <a href="/quality/${escapeHtml(appId)}/">full report</a></p>`;
}

function renderAuditBadge(summary) {
  if (!summary) {
    return '<p class="audit-badge audit-pending"><span class="dot"></span> Not yet audited</p>';
  }
  const total = summary.pass + summary.warn + summary.fail;
  if (summary.fail > 0) {
    return `<p class="audit-badge audit-fail"><span class="dot"></span> ${summary.fail} compliance failure${summary.fail === 1 ? '' : 's'} of ${total} checks &middot; <a href="https://api.freeappstore.online/v1/audit?app=${summary.appId}">details</a></p>`;
  }
  if (summary.warn > 0) {
    return `<p class="audit-badge audit-warn"><span class="dot"></span> ${summary.pass}/${total} compliance checks pass &middot; ${summary.warn} warning${summary.warn === 1 ? '' : 's'}</p>`;
  }
  return `<p class="audit-badge audit-pass"><span class="dot"></span> ${total}/${total} compliance checks pass</p>`;
}

/**
 * Per-app PWA manifest fetch. Used at build time to read the
 * `orientation` + `min_viewport_width` declarations and render the
 * coverage badge on detail pages. Failures → null (badge shows
 * "viewport support unknown" placeholder).
 *
 * Each call is one HTTPS request to {appUrl}/manifest.json. With ~30
 * apps the total is well within rate limits.
 */
function fetchManifest(appUrl) {
  return new Promise((resolve) => {
    try {
      const u = new URL('/manifest.json', appUrl);
      const req = https.request(
        { hostname: u.hostname, path: u.pathname, method: 'GET' },
        (r) => {
          let data = '';
          r.on('data', (c) => (data += c));
          r.on('end', () => {
            if (r.statusCode !== 200) return resolve(null);
            try {
              resolve(JSON.parse(data));
            } catch {
              resolve(null);
            }
          });
        },
      );
      req.on('error', () => resolve(null));
      req.setTimeout(6000, () => {
        req.destroy();
        resolve(null);
      });
      req.end();
    } catch {
      resolve(null);
    }
  });
}

/**
 * Map a min_viewport_width (CSS px) to the rough share of devices that
 * have viewports at least that wide. Numbers come from StatCounter
 * device-share + common-resolution data; this is a directional
 * estimate, not a precision claim — the badge says "approx".
 *
 * Lower min_viewport_width → wider device coverage.
 */
function viewportCoverage(minWidth) {
  if (minWidth <= 320) return 99;
  if (minWidth <= 360) return 96;
  if (minWidth <= 414) return 88;
  if (minWidth <= 600) return 60;
  if (minWidth <= 768) return 35;
  if (minWidth <= 1024) return 20;
  return 10;
}

function renderViewportBadge(manifest) {
  if (!manifest) {
    return '<p class="audit-badge audit-pending"><span class="dot"></span> Viewport support: unknown</p>';
  }
  const orientation = typeof manifest.orientation === 'string' ? manifest.orientation : null;
  const minWidth =
    typeof manifest.min_viewport_width === 'number' ? manifest.min_viewport_width : null;
  if (orientation === null || minWidth === null) {
    return '<p class="audit-badge audit-pending"><span class="dot"></span> Viewport support: not declared</p>';
  }
  const coverage = viewportCoverage(minWidth);
  const orientLabel =
    orientation === 'any'
      ? 'portrait + landscape'
      : orientation === 'portrait' || orientation === 'portrait-primary'
        ? 'portrait only'
        : 'landscape only';
  // Color band: ≥90 green, ≥50 amber, <50 red.
  const cls = coverage >= 90 ? 'audit-pass' : coverage >= 50 ? 'audit-warn' : 'audit-fail';
  return `<p class="audit-badge ${cls}"><span class="dot"></span> Works on ~${coverage}% of devices · ${orientLabel} · min ${minWidth}px wide</p>`;
}

/**
 * Fetch .buildinfo.json from each app's live URL to get the installed size.
 * Written by the deploy workflow. Failures → null (size just doesn't render).
 */
function fetchBuildInfo(appUrl) {
  return new Promise((resolve) => {
    try {
      const u = new URL('/.buildinfo.json', appUrl);
      const req = https.request(
        { hostname: u.hostname, path: u.pathname, method: 'GET' },
        (r) => {
          let data = '';
          r.on('data', (c) => (data += c));
          r.on('end', () => {
            if (r.statusCode !== 200) return resolve(null);
            try {
              resolve(JSON.parse(data));
            } catch {
              resolve(null);
            }
          });
        },
      );
      req.on('error', () => resolve(null));
      req.setTimeout(6000, () => {
        req.destroy();
        resolve(null);
      });
      req.end();
    } catch {
      resolve(null);
    }
  });
}

function formatSize(bytes) {
  if (bytes == null) return null;
  if (bytes === 0) return '0 B';
  if (bytes < 1024) return bytes + ' B';
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(0) + ' KB';
  return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
}

async function fetchCrossStoreRegistry() {
  // Pull the OTHER store's registry so the homepage search can
  // federate. Failure → empty registry, search still works locally.
  return new Promise((resolve) => {
    const req = https.request(
      {
        hostname: 'raw.githubusercontent.com',
        path: '/freegamestore-online/freegamestore/main/registry.json',
        method: 'GET',
      },
      (r) => {
        let data = '';
        r.on('data', (c) => (data += c));
        r.on('end', () => {
          try {
            const parsed = JSON.parse(data);
            resolve({
              items: parsed.games ?? [],
              domain: 'freegamestore.online',
              path: 'games',
            });
          } catch {
            resolve({ items: [], domain: 'freegamestore.online', path: 'games' });
          }
        });
      },
    );
    req.on('error', () => resolve({ items: [], domain: 'freegamestore.online', path: 'games' }));
    req.end();
  });
}

(async () => {
console.log(`Fetching commit history for ${apps.length} apps (with disk cache fallback)...`);
const [histories, auditMap, crossRegistry, manifests, buildInfos] = await Promise.all([
  fetchAllHistories(apps),
  fetchAuditSummary(),
  fetchCrossStoreRegistry(),
  Promise.all(apps.map((a) => fetchManifest(a.appUrl))),
  Promise.all(apps.map((a) => fetchBuildInfo(a.appUrl))),
]);

// Stamp each card with data-published from the fetched history, then inject
// the grid into the index HTML. This is done here (inside the async IIFE) so
// histories are available; the {{APPS_GRID}} placeholder was intentionally
// left unreplaced in the synchronous setup above.
const appCards = apps.map((app, i) => {
  const published = histories[i]?.meta?.created_at ?? null;
  return renderAppCard(app, published);
}).join('\n\n');

// Now finalize and write the index page with the embedded cross-store
// registry so the search bar can federate.
indexHtml = indexHtml
  .replace('{{APPS_GRID}}', appCards)
  .replace(
    '{{CROSS_STORE_REGISTRY}}',
    JSON.stringify(crossRegistry).replace(/</g, '\\u003c'),
  );
fs.writeFileSync(path.join(DIST, 'index.html'), indexHtml);

// --- Settings page ---
const settingsTemplate = injectPartials(fs.readFileSync(path.join(ROOT, 'templates', 'settings.html'), 'utf8'));
let settingsHtml = settingsTemplate.replace('__CF_BEACON__', CF_BEACON_SNIPPET);
for (const [k, v] of Object.entries(sriHashes)) {
  settingsHtml = settingsHtml.replaceAll(`{{SRI_${k}}}`, v);
}
for (const [k, v] of Object.entries(contentVersions)) {
  settingsHtml = settingsHtml.replaceAll(`{{VER_${k}}}`, v);
}
fs.writeFileSync(path.join(DIST, 'settings.html'), settingsHtml);

// Per-card icon backgrounds (registry-driven). Lives in its own file so
// a malformed iconBg slipping past validation can never become an inline
// style attribute on the card itself.
fs.writeFileSync(path.join(DIST, 'card-styles.css'), cardIconBackgrounds + '\n');

// --- Quality Dashboard ---
// Embeds both the local apps registry and the cross-store games registry
// so visitors can audit either from one page. The page is mostly static —
// the live iframe + postMessage logic lives in /quality.js.
const qualityTemplate = injectPartials(fs.readFileSync(path.join(ROOT, 'templates', 'quality.html'), 'utf8'));
const qualityRegistry = {
  apps: apps.map(a => ({ id: a.id, name: a.name, appUrl: a.appUrl })),
  games: (crossRegistry.items || []).map(g => ({ id: g.id, name: g.name, appUrl: g.appUrl })),
  // Platform fixtures — deliberately-broken control cases used to verify
  // the auditor flags each layout-bug class correctly. Visible from the
  // /quality dashboard but filtered out of the main store browse.
  fixtures: [
    { id: 'auditor-fixture', name: 'Auditor Fixture', appUrl: '/audit-fixture/', fixture: true,
      description: 'Deliberately-broken control cases. Each scenario reproduces a known layout bug to verify the platform auditor flags it correctly.' },
  ],
};
// Build code quality cards for the quality page
const codeQualityCards = apps
  .map(app => {
    const q = qualityScores[app.id];
    if (!q || !q.grade) return '';
    const gradeClass = q.score >= 80 ? 'ok' : q.score >= 60 ? 'warn' : 'bad';
    return `<a href="/quality/${escapeHtml(app.id)}/" class="q-card"><div class="q-card-head"><span class="name">${escapeHtml(app.name)}</span><span class="index ${gradeClass}">${q.grade}</span></div><div class="meta">${q.score}/100</div></a>`;
  })
  .filter(Boolean)
  .join('\n        ');

let qualityHtml = qualityTemplate
  .replace('__CF_BEACON__', CF_BEACON_SNIPPET)
  .replace('{{CODE_QUALITY_CARDS}}', codeQualityCards)
  .replace('{{REGISTRIES_JSON}}', JSON.stringify(qualityRegistry).replace(/</g, '\\u003c'));
for (const [k, v] of Object.entries(sriHashes)) {
  qualityHtml = qualityHtml.replaceAll(`{{SRI_${k}}}`, v);
}
for (const [k, v] of Object.entries(contentVersions)) {
  qualityHtml = qualityHtml.replaceAll(`{{VER_${k}}}`, v);
}
fs.writeFileSync(path.join(DIST, 'quality.html'), qualityHtml);
console.log(`  /quality dashboard generated for ${qualityRegistry.apps.length} apps + ${qualityRegistry.games.length} games`);
console.log(`  ${crossRegistry.items.length} games available for cross-store search`);
// Summarize: count how many apps got real commit data vs fell back.
const okCount = histories.filter((h) => Array.isArray(h?.commits) && h.commits.length > 0).length;
console.log(`  ${okCount}/${apps.length} apps got commit history`);
console.log(`  ${auditMap.size} apps have audit results`);

apps.forEach((app, i) => {
  const offline = app.type === 'standalone' ? 'Yes' : 'When cached';
  const account = app.type === 'standalone' ? 'Not required' : 'Not required';
  const history = histories[i];

  // Every user-controlled registry field gets HTML-escaped before
  // substitution into the detail template — without this a malicious or
  // accidentally-mistyped description like `<script>alert(1)</script>`
  // would render as a working tag (test/build.test.mjs locks this in).
  // `icon` is the one deliberate exception: it's a pre-encoded HTML
  // entity (e.g. "&#127463;") that registry maintainers author, so
  // we pass it through raw. `id` is a slug constrained by the publish
  // pipeline and used inside URLs / JS strings, but we still escape it
  // for defense in depth.
  let html = detailTemplate
    .replace('__CF_BEACON__', CF_BEACON_SNIPPET)
    .replace(/\{\{NAME\}\}/g, escapeHtml(app.name))
    .replace(/\{\{NAME_LOWER\}\}/g, escapeHtml(app.name.toLowerCase()))
    .replace(/\{\{ID\}\}/g, escapeHtml(app.id))
    .replace(/\{\{ICON\}\}/g, app.icon)
    .replace(/\{\{LETTER\}\}/g, escapeHtml((app.name || '?').trim().charAt(0).toUpperCase()))
    .replace(/\{\{ICON_BG\}\}/g, escapeHtml(app.iconBg))
    .replace(/\{\{CATEGORY_LABEL\}\}/g, escapeHtml(categoryLabel(app.category)))
    .replace(/\{\{DESCRIPTION\}\}/g, escapeHtml(app.description))
    .replace(/\{\{APP_URL\}\}/g, escapeHtml(app.appUrl))
    .replace(/\{\{REPO\}\}/g, escapeHtml(app.repo))
    .replace(/\{\{TYPE_LABEL\}\}/g, escapeHtml(typeLabel(app.type)))
    .replace(/\{\{DEVELOPER\}\}/g, escapeHtml(app.developer))
    .replace(/\{\{AUTHOR_CHIP\}\}/g, renderAuthorChip(app))
    .replace(/\{\{OFFLINE\}\}/g, escapeHtml(offline))
    .replace(/\{\{ACCOUNT\}\}/g, escapeHtml(account))
    .replace(/\{\{PUBLISHED_LINE\}\}/g, renderPublishedLine(history))
    .replace(/\{\{HISTORY_SECTION\}\}/g, renderHistorySection(app.repo, history))
    .replace(/\{\{AUDIT_BADGE\}\}/g, renderAuditBadge(auditMap.get(app.id)))
    .replace(/\{\{CODE_QUALITY_BADGE\}\}/g, renderCodeQualityBadge(app.id))
    .replace(/\{\{VIEWPORT_BADGE\}\}/g, renderViewportBadge(manifests[i]))
    .replace(/\{\{SIZE\}\}/g, formatSize(buildInfos[i]?.size) || 'Unknown');

  // SRI hashes and content-version tokens (detail pages use auth.js + detail-page.js).
  for (const [k, v] of Object.entries(sriHashes)) {
    html = html.replaceAll(`{{SRI_${k}}}`, v);
  }
  for (const [k, v] of Object.entries(contentVersions)) {
    html = html.replaceAll(`{{VER_${k}}}`, v);
  }

  fs.writeFileSync(path.join(DIST, 'apps', `${app.id}.html`), html);
});

// --- Generate per-author profile pages at /u/<username>.html ---
//
// One page per unique creatorGithub across the registry. Pulls the avatar
// from GitHub at render time (img tag, no API call here), lists every app
// that author published. Apps without creatorGithub don't get an author
// page — they render as plain "by FreeAppStore" text via renderAuthorChip.
const authorTemplate = injectPartials(fs.readFileSync(path.join(ROOT, 'templates', 'author.html'), 'utf8'));
const uniqueAuthors = [...new Set(apps.map(a => a.creatorGithub).filter(Boolean))];
fs.mkdirSync(path.join(DIST, 'u'), { recursive: true });

/**
 * Derive earned-badges for one author from the apps they published.
 *
 * Pure-function from registry data — no DB schema, no per-author state to
 * maintain. New rules should follow the same pattern: read authorApps +
 * the existing qualityScores / auditMap closures, push `{icon,label,title}`
 * objects, return them. Tooltip on hover comes from `title`; the rendered
 * chip is just `icon label`.
 */
function computeAuthorBadges(authorApps) {
  const badges = [];
  const count = authorApps.length;
  if (count >= 1)  badges.push({ icon: '🚀', label: 'First publication', title: 'Has at least one app published on FreeAppStore.' });
  if (count >= 5)  badges.push({ icon: '⚡', label: 'Prolific', title: 'Published 5 or more apps.' });
  if (count >= 10) badges.push({ icon: '🏗️', label: 'Established', title: 'Published 10 or more apps.' });
  if (count >= 25) badges.push({ icon: '👑', label: 'Top creator', title: 'Published 25 or more apps.' });

  // Multi-category: counts distinct categories case-insensitively (registry
  // currently has both 'social' and 'Social' as legacy duplicates; treat them
  // as one for the badge rule until that hygiene gets cleaned up elsewhere).
  const cats = new Set(authorApps.map((a) => String(a.category || '').toLowerCase()).filter(Boolean));
  if (cats.size >= 3) {
    badges.push({ icon: '🎨', label: 'Multi-category', title: `Apps span ${cats.size} distinct categories.` });
  }

  // Quality champion: ≥75% of this author's quality-graded apps scored A.
  const graded = authorApps.filter((a) => qualityScores[a.id]?.grade);
  if (graded.length >= 3) {
    const aCount = graded.filter((a) => qualityScores[a.id].grade === 'A').length;
    if (aCount / graded.length >= 0.75) {
      badges.push({
        icon: '⭐',
        label: 'Quality champion',
        title: `${aCount} of ${graded.length} graded apps scored A.`,
      });
    }
  }

  // Audited: ≥75% of this author's apps have a registered audit result.
  // Lower fraction = no badge (correctly stays dark for partial coverage).
  if (count >= 3) {
    const audited = authorApps.filter((a) => auditMap.get(a.id)).length;
    if (audited / count >= 0.75) {
      badges.push({
        icon: '✅',
        label: 'Audited',
        title: `${audited} of ${count} apps have passed platform audits.`,
      });
    }
  }
  return badges;
}

function renderBadges(badges) {
  if (badges.length === 0) return '';
  const items = badges
    .map(
      (b) =>
        `        <span class="badge" title="${escapeHtml(b.title)}"><span class="badge-icon">${b.icon}</span><span class="badge-label">${escapeHtml(b.label)}</span></span>`,
    )
    .join('\n');
  return `<div class="badges">\n${items}\n      </div>`;
}

uniqueAuthors.forEach(username => {
  const authorApps = apps.filter(a => a.creatorGithub === username);
  const appCardsHtml = authorApps.map(renderAppCard).join('\n\n');
  const badges = computeAuthorBadges(authorApps);
  let html = authorTemplate
    .replace('__CF_BEACON__', CF_BEACON_SNIPPET)
    .replace(/\{\{USERNAME\}\}/g, escapeHtml(username))
    .replace(/\{\{APP_COUNT\}\}/g, String(authorApps.length))
    .replace(/\{\{S\}\}/g, authorApps.length === 1 ? '' : 's')
    .replace(/\{\{BADGES\}\}/g, renderBadges(badges))
    .replace(/\{\{APP_CARDS\}\}/g, appCardsHtml);
  for (const [k, v] of Object.entries(sriHashes)) {
    html = html.replaceAll(`{{SRI_${k}}}`, v);
  }
  for (const [k, v] of Object.entries(contentVersions)) {
    html = html.replaceAll(`{{VER_${k}}}`, v);
  }
  fs.writeFileSync(path.join(DIST, 'u', `${username}.html`), html);
});
console.log(`Generated ${uniqueAuthors.length} author page(s) at /u/`);

// --- Generate /developers index page ---
const creatorsTemplate = injectPartials(fs.readFileSync(path.join(ROOT, 'templates', 'creators.html'), 'utf8'));
const devCards = uniqueAuthors.map(username => {
  const authorApps = apps.filter(a => a.creatorGithub === username);
  const badges = computeAuthorBadges(authorApps);
  const badgesHtml = badges.length > 0
    ? `<div class="dev-badges">${badges.map(b => `<span class="dev-badge" title="${escapeHtml(b.title)}">${b.icon} ${escapeHtml(b.label)}</span>`).join('')}</div>`
    : '';
  return `        <a class="dev-card" href="/u/${escapeHtml(username)}.html">
          <img class="dev-avatar" src="https://avatars.githubusercontent.com/${escapeHtml(username)}?size=200" alt="" loading="lazy" />
          <div class="dev-card-body">
            <span class="dev-card-name">@${escapeHtml(username)}</span>
            ${badgesHtml}
            <span class="dev-card-stats">${authorApps.length} app${authorApps.length === 1 ? '' : 's'}</span>
          </div>
        </a>`;
}).join('\n');

let creatorsHtml = creatorsTemplate
  .replace('__CF_BEACON__', CF_BEACON_SNIPPET)
  .replace('{{DEVELOPERS_GRID}}', devCards);
for (const [k, v] of Object.entries(sriHashes)) {
  creatorsHtml = creatorsHtml.replaceAll(`{{SRI_${k}}}`, v);
}
for (const [k, v] of Object.entries(contentVersions)) {
  creatorsHtml = creatorsHtml.replaceAll(`{{VER_${k}}}`, v);
}
fs.writeFileSync(path.join(DIST, 'creators.html'), creatorsHtml);
console.log(`Generated /creators page (${uniqueAuthors.length} creators)`);

// --- Generate sitemap.xml ---

const today = new Date().toISOString().split('T')[0];
const sitemapEntries = [
  `  <url><loc>https://freeappstore.online/</loc><lastmod>${today}</lastmod><priority>1.0</priority></url>`,
  `  <url><loc>https://freeappstore.online/about.html</loc><lastmod>${today}</lastmod><priority>0.8</priority></url>`,
  `  <url><loc>https://freeappstore.online/contribute.html</loc><lastmod>${today}</lastmod><priority>0.7</priority></url>`,
  `  <url><loc>https://freeappstore.online/get-started.html</loc><lastmod>${today}</lastmod><priority>0.9</priority></url>`,
  `  <url><loc>https://freeappstore.online/pricing.html</loc><lastmod>${today}</lastmod><priority>0.8</priority></url>`,
  `  <url><loc>https://freeappstore.online/build-with-ai.html</loc><lastmod>${today}</lastmod><priority>0.85</priority></url>`,
  `  <url><loc>https://freeappstore.online/ai/claude-code.html</loc><lastmod>${today}</lastmod><priority>0.7</priority></url>`,
  `  <url><loc>https://freeappstore.online/ai/cursor.html</loc><lastmod>${today}</lastmod><priority>0.7</priority></url>`,
  `  <url><loc>https://freeappstore.online/ai/github-copilot.html</loc><lastmod>${today}</lastmod><priority>0.7</priority></url>`,
  `  <url><loc>https://freeappstore.online/ai/aider.html</loc><lastmod>${today}</lastmod><priority>0.7</priority></url>`,
  `  <url><loc>https://freeappstore.online/ai/codex.html</loc><lastmod>${today}</lastmod><priority>0.7</priority></url>`,
  `  <url><loc>https://freeappstore.online/ai/windsurf.html</loc><lastmod>${today}</lastmod><priority>0.7</priority></url>`,
  `  <url><loc>https://freeappstore.online/ai/zed.html</loc><lastmod>${today}</lastmod><priority>0.7</priority></url>`,
  `  <url><loc>https://freeappstore.online/ai/continue.html</loc><lastmod>${today}</lastmod><priority>0.7</priority></url>`,
  `  <url><loc>https://freeappstore.online/ai/cline.html</loc><lastmod>${today}</lastmod><priority>0.7</priority></url>`,
  `  <url><loc>https://freeappstore.online/ai/chatgpt-web.html</loc><lastmod>${today}</lastmod><priority>0.7</priority></url>`,
  `  <url><loc>https://docs.freeappstore.online/</loc><lastmod>${today}</lastmod><priority>0.85</priority></url>`,
  `  <url><loc>https://freeappstore.online/capabilities.html</loc><lastmod>${today}</lastmod><priority>0.85</priority></url>`,
  `  <url><loc>https://freeappstore.online/browser-apis.html</loc><lastmod>${today}</lastmod><priority>0.85</priority></url>`,
  `  <url><loc>https://freeappstore.online/skills.md</loc><lastmod>${today}</lastmod><priority>0.9</priority></url>`,
  `  <url><loc>https://freeappstore.online/llms.txt</loc><lastmod>${today}</lastmod><priority>0.7</priority></url>`,
  `  <url><loc>https://freeappstore.online/quality.html</loc><lastmod>${today}</lastmod><priority>0.7</priority></url>`,
  `  <url><loc>https://freeappstore.online/creators</loc><lastmod>${today}</lastmod><priority>0.7</priority></url>`,
  `  <url><loc>https://freeappstore.online/privacy.html</loc><lastmod>${today}</lastmod><priority>0.5</priority></url>`,
  `  <url><loc>https://freeappstore.online/terms.html</loc><lastmod>${today}</lastmod><priority>0.5</priority></url>`,
  ...apps.map(app =>
    `  <url><loc>https://freeappstore.online/apps/${app.id}.html</loc><lastmod>${today}</lastmod><priority>0.9</priority></url>`
  ),
  ...uniqueAuthors.map(username =>
    `  <url><loc>https://freeappstore.online/u/${username}.html</loc><lastmod>${today}</lastmod><priority>0.6</priority></url>`
  )
];

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemapEntries.join('\n')}
</urlset>
`;

fs.writeFileSync(path.join(DIST, 'sitemap.xml'), sitemap);

// --- Copy static assets ---

const filesToCopy = [
  'style.css',
  'search.js',
  'storefront.js',
  'detail-page.js',
  'quality.js',
  'analytics.js',
  'manifest.json',
  'favicon.svg',
  'apple-touch-icon.png',
  'icon-192.png',
  'icon-512.png',
  'robots.txt',
  '404.html',
  'about.html',
  'contribute.html',
  'privacy.html',
  'terms.html',
  'build-with-ai.html',
  'pricing.html',
  'get-started.html',
  'get-started.js',
  'analytics.html',
  'auth.js',
  'prism.js',
  'prism-autodetect.js',
  'settings.js',
  '_redirects',
];

// Security headers via CF Pages _headers — single source of truth for CSP and
// every other security header. <meta> CSP is intentionally absent (frame-ancestors,
// report-to, sandbox, and HSTS can't ride in <meta> anyway). The script-src
// hash is computed at build time so the inline no-flash theme bootstrap is the
// ONLY inline JS the page allows.
const csp = [
  "default-src 'self'",
  "img-src 'self' https://*.freeappstore.online https://*.freegamestore.online https://avatars.githubusercontent.com data:",
  `script-src 'self' '${inlineScriptHash}' https://static.cloudflareinsights.com`,
  "style-src 'self' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com",
  "connect-src 'self' https://*.freeappstore.online https://api.freeappstore.online https://cloudflareinsights.com",
  "frame-src https://*.freeappstore.online https://*.freegamestore.online https://*.proappstore.online",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self' https://api.freeappstore.online",
  "object-src 'none'",
  "upgrade-insecure-requests",
  // CSP3 reporting (newer). `report-uri` kept for browsers that pre-date `report-to`.
  "report-to csp-endpoint",
  "report-uri /v1/csp-report",
].join('; ');

fs.writeFileSync(path.join(DIST, '_headers'), [
  '/*',
  '  X-Frame-Options: DENY',
  '  X-Content-Type-Options: nosniff',
  '  Referrer-Policy: strict-origin-when-cross-origin',
  '  Strict-Transport-Security: max-age=31536000; includeSubDomains',
  '  Cross-Origin-Opener-Policy: same-origin',
  '  Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=(), midi=()',
  // Reporting group referenced by CSP `report-to`. Same-origin endpoint
  // handled by functions/v1/csp-report.js.
  '  Reporting-Endpoints: csp-endpoint="/v1/csp-report"',
  `  Content-Security-Policy: ${csp}`,
  `  Content-Security-Policy-Report-Only: ${csp}`,
  '',
  '# Immutable cache for versioned assets. JS and CSS are referenced with a',
  '# content-hash query param (?v=<hash>) injected at build time, so the URL',
  '# changes whenever the file changes. The edge may cache forever — a stale',
  '# URL is never served because fresh HTML always points at the new URL.',
  '/*.css',
  '  Cache-Control: public, max-age=31536000, immutable',
  '/*.js',
  '  Cache-Control: public, max-age=31536000, immutable',
  '/*.png',
  '  Cache-Control: public, max-age=604800, immutable',
  '/*.svg',
  '  Cache-Control: public, max-age=604800, immutable',
  '',
].join('\n'));

// Copy static assets. .html files get a substitution pass for {{SRI_*}} and
// {{VER_*}} placeholders so integrity attributes and versioned src URLs match
// the just-computed hashes — same pipeline as the index template. Everything
// else is binary-copied.
filesToCopy.forEach(file => {
  const src = path.join(ROOT, file);
  if (!fs.existsSync(src)) return;
  const dst = path.join(DIST, file);
  if (file.endsWith('.html')) {
    let html = fs.readFileSync(src, 'utf8');
    html = injectPartials(html);
    for (const [k, v] of Object.entries(sriHashes)) {
      html = html.replaceAll(`{{SRI_${k}}}`, v);
    }
    for (const [k, v] of Object.entries(contentVersions)) {
      html = html.replaceAll(`{{VER_${k}}}`, v);
    }
    html = html.replaceAll('__CF_BEACON__', CF_BEACON_SNIPPET);
    if (/{{SRI_[A-Z_]+}}/.test(html)) {
      console.error(`Unsubstituted {{SRI_*}} placeholder in ${file}`);
      process.exit(1);
    }
    fs.writeFileSync(dst, html);
  } else {
    fs.copyFileSync(src, dst);
  }
});

// SDK docs pages under /docs/<slug>.html.
const docsSrcDir = path.join(ROOT, 'docs');
if (fs.existsSync(docsSrcDir)) {
  const docsDestDir = path.join(DIST, 'docs');
  fs.mkdirSync(docsDestDir, { recursive: true });
  for (const f of fs.readdirSync(docsSrcDir)) {
    if (!f.endsWith('.html')) continue;
    let html = fs.readFileSync(path.join(docsSrcDir, f), 'utf8');
    for (const [k, v] of Object.entries(sriHashes)) {
      html = html.replaceAll(`{{SRI_${k}}}`, v);
    }
    for (const [k, v] of Object.entries(contentVersions)) {
      html = html.replaceAll(`{{VER_${k}}}`, v);
    }
    html = html.replaceAll('__CF_BEACON__', CF_BEACON_SNIPPET);
    fs.writeFileSync(path.join(docsDestDir, f), html);
  }
}

// AI tool guides — one HTML file per tool (claude-code, cursor, etc.).
// They live under /ai/<slug>.html so the URL space stays clean.
const aiSrcDir = path.join(ROOT, 'ai');
if (fs.existsSync(aiSrcDir)) {
  const aiDestDir = path.join(DIST, 'ai');
  fs.mkdirSync(aiDestDir, { recursive: true });
  for (const f of fs.readdirSync(aiSrcDir)) {
    if (!f.endsWith('.html')) continue;
    fs.copyFileSync(path.join(aiSrcDir, f), path.join(aiDestDir, f));
  }
}

// Auditor fixture under /audit-fixture/. Single static page with
// query-param-driven scenarios — see audit-fixture/index.html for the
// scenarios + their expected audit verdicts. Hosted same-origin so the
// /quality dashboard can iframe it without any CORS dance. Mirror of
// the fgs storefront's deploy.
const fixtureSrcDir = path.join(ROOT, 'audit-fixture');
if (fs.existsSync(fixtureSrcDir)) {
  const fixtureDestDir = path.join(DIST, 'audit-fixture');
  fs.mkdirSync(fixtureDestDir, { recursive: true });
  for (const f of fs.readdirSync(fixtureSrcDir)) {
    fs.copyFileSync(path.join(fixtureSrcDir, f), path.join(fixtureDestDir, f));
  }
}

// .well-known/ — MCP discovery and other standards
const wellKnownSrc = path.join(ROOT, '.well-known');
if (fs.existsSync(wellKnownSrc)) {
  const wellKnownDest = path.join(DIST, '.well-known');
  fs.mkdirSync(wellKnownDest, { recursive: true });
  for (const f of fs.readdirSync(wellKnownSrc)) {
    fs.copyFileSync(path.join(wellKnownSrc, f), path.join(wellKnownDest, f));
  }
}

// llms.txt → dist (AI agent discovery, like robots.txt but for LLMs)
const llmsSrc = path.join(ROOT, 'llms.txt');
if (fs.existsSync(llmsSrc)) {
  fs.copyFileSync(llmsSrc, path.join(DIST, 'llms.txt'));
}

// Markdown files → dist (lowercase for URL compatibility)
for (const md of ['SKILLS.md', 'claude-code.md']) {
  const src = path.join(ROOT, md);
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, path.join(DIST, md.toLowerCase()));
  }
}

console.log(`Built ${apps.length} app cards into dist/index.html`);
console.log(`Generated ${apps.length} detail pages in dist/apps/`);
console.log('Generated dist/sitemap.xml');
console.log('Copied static assets');
})().catch((err) => {
  console.error('build failed:', err);
  process.exit(1);
});
